# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crowd-stefanwille}
  s.version = "0.5.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Wille", "Evgeny Zislis", "Jason Rimmer & Daniel Morrison"]
  s.date = %q{2010-07-26}
  s.description = %q{A client for Atlassian[http://www.atlassian.com] Crowd[http://www.atlassian.com/crowd] v2.0. Tested with Crowd 2.0.2 and 2.0.5.}
  s.email = %q{post @nospam@ stefanwille.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README.rdoc",
     "Rakefile",
     "crowd-stefanwille.gemspec",
     "demo/crowd_demo.rb",
     "lib/crowd.rb",
     "lib/crowd/http/request.rb",
     "lib/crowd/http/response.rb",
     "lib/crowd/http/sso.rb",
     "lib/crowd/soap/SecurityServerClient.rb",
     "lib/crowd/soap/crowd-2.0.5.wsdl",
     "lib/crowd/soap/default.rb",
     "lib/crowd/soap/driver.rb",
     "lib/crowd/soap/mapping_registry.rb",
     "lib/crowd/user_attribute_keys.rb",
     "lib/crowd/version.rb",
     "spec/crowd_spec.rb"
  ]
  s.homepage = %q{http://github.com/stefanwille/crowd}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nowarning}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby client for Atlassian Crowd 2.0}
  s.test_files = [
    "spec/crowd_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<soap4r>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<soap4r>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<soap4r>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

